name: Dopamine CI CD

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: dopamine
  AZURE_WEBAPP_PACKAGE_PATH: '.'
  NODE_VERSION: '20.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run tests (optional but recommended)
      - name: Run Tests
        run: npm test || echo "Tests failed, continuing deployment..."

      # Step 5: Build the project (if build script exists)
      - name: Build Project
        run: run: CI=false npm run build --if-present

      # Step 6: Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 7: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      # Step 8: Logout from Azure
      - name: Azure Logout
        run: az logout

